export const LOCAL_STORAGE_AGREEMENT_MAPPING_KEY =
  "LOCAL_STORAGE_AGREEMENT_MAPPING_KEY";
export const LOCAL_STORAGE_PASSWORD_MAPPING_KEY =
  "LOCAL_STORAGE_PASSWORD_MAPPING_KEY";
export const LOCAL_STORAGE_PROOF_KEY = "LOCAL_STORAGE_PROOF_KEY";
